### ISSUE TITLE
PN of MainConnector

### ISSUE THREAD

**Issue by Marcelocm1995** [oelprinz-org/BlitzboxBL49sp#13]
Hi, I'm doing this project and I need de part number or link to buy the MainConnector, I did not found inside documentation.

Best Regards

**Comment by chaoschris** [comment]
Ola Marcelo,

todas as informacoes que vc precisa vc vai encontrar no blogue/forum do speeduino:
https://speeduino.com/forum/viewtopic.php?p=61573#p61573

Para completar o conector este pagina ai pode ajudar:   http://www.oelprinz.org/products/BlitzboxBL49sp/documentation/V0.1.4/wiki/pinout_V0.1.4_Connector_top_side.html

Vc pode me respostar em portugues tambem, e sem pro para mim....

**Comment by Marcelocm1995** [comment]
Que legal, parabens pelo projeto. E muito obrigado! Vc poderia me passar algum contato caso aceite um trabalho freelancer? Tenho uma demanda.

Grato

**Comment by chaoschris** [comment]
Infelizmente esto uma pessoa privada e nao uma compania......

**Comment by Marcelocm1995** [comment]
Chirs, minhas PCB chegaram. Gravei os bootloaders, porem nao consigo gravar o software do speeduino via xloader, nem um blink para o 2560. Tentei via 5v e RXD TXD (do bluetooth conector usando um FTDI) e tambem via USB com o Silabs integrado, ambos sem sucesso. Usando o FTDI consegui gravar o 328p referente a wideband. Alguma sugestão?

**Comment by chaoschris** [comment]
Ola Marcelo, voce pode conferir os fuses? 

No 2560 tenho de ser:
L   0xFF
H   0xD8
E   0xFD
LB  0xCF

e no 328p:
L   0xFF
H   0xDA
E   0xFD
LB  0xCF

**Comment by Marcelocm1995** [comment]
Acabei de conseguir! Fazendo o seguinte:

Via Silabs integrado eu fiz um jumper entre VBUS e 5V.

Curioso via RXD TXD com FTDI nao ir, irei colocar um modulo bluetooth para testar. Seria o HC-05?

**Comment by chaoschris** [comment]
Isso e feito de proposito assim! E melhor de separar o fonte 5V do USB. Como vc fiz somente funciona se vc bota 12V no UB+

**Comment by chaoschris** [comment]
>> Seria o HC-05?
Normalmente todos os modulos BT que tenho serial vai funcionar se vc vai configurar eles antes para 115200....

**Comment by Marcelocm1995** [comment]
Entendi, muito obrigado. Irei comecar a testar com o TunerStudio
