### ISSUE TITLE
Crank and cam input

### ISSUE THREAD

**Issue by runesmdk** [oelprinz-org/BlitzboxBL49sp#14]
Straight from jlcpcb, is crankshaft then ready for vr or hall? What mods to swap sensor type on crank? And same for cam, what sensortype, and what mods to swap sensor type?

**Comment by chaoschris** [comment]
With the soldered max9926 both inputs are ready for vr signals. In my opinion VR is the most common solution for crankshaft and the max9926 is one of the best solutions on the market for vr signals. 

Camshaft input is mostly a square hall signal. But in this configuration the camshaft input can handle very well a single hall signal every 720 degrees. 
- For 5V Hall input VR- should go to GND. 
- If you have a 12V Hall Signal, it would be a good point to start with +5V on VR- . There is a soldering bridge on the board to do this (SJ5).

The same wiring you can apply on the crankshaft input if you want to use hall input WITH the soldered MAX9926. But here you don't have a soldering bridge onboard and you have to wire it externally or direct on the board which is easy to do.

**Comment by chaoschris** [comment]
closed
