### ISSUE TITLE
[solved] V 0.1.2 speeduino firmware stops working when pulling the USB plug

### ISSUE THREAD

**Issue by chaoschris** [oelprinz-org/BlitzboxBL49sp#5]
V 0.1.2 speeduino firmware stops working when pulling the USB plug.
With the USB plug connected all works fine

**Comment by SW65** [comment]
Und was haben die als Lösung?

**Comment by chaoschris** [comment]
Shutting down the power supply of the Cp2102 converter chip leads to a constant voltage level of 0 V on the RX line of the Atmega2560. This can be fixed temporary with a 10k Pullup from RX to +5V as shown in the picture. Further investigation will follow soon before the next/final pcb revision.
![RX_Pullup_1ok](https://user-images.githubusercontent.com/42533712/165131651-6544312a-db7a-48ae-af08-ae1adf7c4e14.png)

**Comment by SW65** [comment]
Lösung ist halt ohne Zigarettenanzünder mit usb Kabel und kleiner:-)
Liegt nicht an der Firmware?

Melde mich später mal .

Grüße Jörg

**Comment by chaoschris** [comment]
Doesn't look like a firmware issue. The original Arduino Mega 2560 design also has two inline resistors with 1K on RX and TX. Will have a deeper look on this later.

**Comment by chaoschris** [comment]
solved in V0.1.3

**Comment by chaoschris** [comment]
solved in V0.1.3
