### ISSUE TITLE
stepper idle motor

### ISSUE THREAD

**Issue by giuliovalcanaia** [oelprinz-org/BlitzboxBL49sp#7]
First thing: congratulations on the project, it is really good. Second thing: Any chance of adding stepper motor support?

**Comment by chaoschris** [comment]
There ist absolutely no space  top add stepper support on this board. If you really need a stepper you can use the upcoming Gewitterbox design here in our GitHub repository when it is ready for production some day.

**Comment by Ricardo29410** [comment]
Hello, a pleasure Ricardo Rodríguez I'm from Venezuela and your plate
really catches my attention and I want to try both models
