### ISSUE TITLE
Missing wideband controller?

### ISSUE THREAD

**Issue by abreumatheus** [oelprinz-org/BlitzboxBL49sp#9]
Hi, first thank you for your amazing work on this.
I noticed the bosch wideband controller chip is missing on the bom. 
Is it ok to order it sepparetly and solder it by hand?

Greetings from Brazil.

**Comment by chaoschris** [comment]
Ola Matheus,
JLC nao vai soldar este CJ125 na placa pq eles nao oferece algumes partes especial, mesmo se era possivel de comprar as pecas anterior. Entao vc tenho de soldar este peca....
Um abraco
Chris

**Comment by abreumatheus** [comment]
Thank you for the heads up!
Muito obrigado! 😁
